# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random walk approximation to a single trajectory in Drift-Diffusion Model
#'
#' Simulates a random walk with step sizes that are the square root of a
#' discrete time step t_eps. As t_eps -> 0, this random walk converges to a
#' drift-diffusion model.
#'
#' @param b Starting point in terms of proportion of distance from 0 to a.
#' @param a Upper barrier (lower is 0)
#' @param v Drift rate
#' @param t_eps Time step size
#'
#' @export
random_walk <- function(b, a, v, t_eps = 1e-4) {
    .Call(`_norbertr_random_walk`, b, a, v, t_eps)
}

